[object Object],
,[object Object],
,[object Object],
    ,[object Object],
    ,[object Object],
    ,[object Object],Система управління дронами,[object Object],
    ,[object Object],[object Object],[object Object],
,[object Object],
,[object Object],
    ,[object Object],
        ,[object Object],
            ,[object Object],Вхід,[object Object],
            ,[object Object],Польоти,[object Object],
            ,[object Object],Повідомлення,[object Object],
        ,[object Object],

        ,[object Object],
        ,[object Object],
            ,[object Object],Вхід у систему,[object Object],
            ,[object Object],[object Object],
            
            ,[object Object],
                ,[object Object],Ім'я користувача:,[object Object],
                ,[object Object],
            ,[object Object],

            ,[object Object],
                ,[object Object],Email:,[object Object],
                ,[object Object],
            ,[object Object],

            ,[object Object],
                ,[object Object],Пароль:,[object Object],
                ,[object Object],
            ,[object Object],

            ,[object Object],
                ,[object Object],Телефон:,[object Object],
                ,[object Object],
            ,[object Object],

            ,[object Object],Увійти,[object Object],
            ,[object Object],Очистити дані,[object Object],

            ,[object Object],
                📝 Дані будуть автоматично збережені після входу
            ,[object Object],
        ,[object Object],

        ,[object Object],
        ,[object Object],
            ,[object Object],Управління польотами,[object Object],
            ,[object Object],[object Object],

            ,[object Object],
                ,[object Object],Виберіть модель дрона:,[object Object],
                ,[object Object],
                    ,[object Object],-- Виберіть дрон --,[object Object],
                    ,[object Object],DJI Phantom 4 Pro,[object Object],
                    ,[object Object],DJI Mavic 3,[object Object],
                    ,[object Object],DJI Air 3,[object Object],
                    ,[object Object],Auterion Skynode,[object Object],
                ,[object Object],
            ,[object Object],

            ,[object Object],
                ,[object Object],Серійний номер дрона:,[object Object],
                ,[object Object],
            ,[object Object],

            ,[object Object],[object Object],

            ,[object Object],Додати новий зліт,[object Object],

            ,[object Object],
                ,[object Object],Локація зліту:,[object Object],
                ,[object Object],
            ,[object Object],

            ,[object Object],
                ,[object Object],Тривалість (хвилини):,[object Object],
                ,[object Object],
            ,[object Object],

            ,[object Object],
                ,[object Object],Висота (метри):,[object Object],
                ,[object Object],
            ,[object Object],

            ,[object Object],
                ,[object Object],Примітки:,[object Object],
                ,[object Object],[object Object],
            ,[object Object],

            ,[object Object],Додати зліт,[object Object],

            ,[object Object],
                ,[object Object],Список злітів,[object Object],
                ,[object Object],[object Object],
            ,[object Object],
        ,[object Object],

        ,[object Object],
        ,[object Object],
            ,[object Object],Генерування повідомлення для Telegram,[object Object],
            ,[object Object],[object Object],

            ,[object Object],
                ,[object Object],📱 Інформація сеансу,[object Object],
                ,[object Object],[object Object],Користувач:,[object Object], ,[object Object],не авторизований,[object Object],[object Object],
                ,[object Object],[object Object],Дрон:,[object Object], ,[object Object],не вибран,[object Object],[object Object],
                ,[object Object],[object Object],Серійний номер:,[object Object], ,[object Object],не вказаний,[object Object],[object Object],
                ,[object Object],[object Object],Всього польотів:,[object Object], ,[object Object],0,[object Object],[object Object],
            ,[object Object],

            ,[object Object],
                ,[object Object],Текст повідомлення:,[object Object],
                ,[object Object],[object Object],
            ,[object Object],

            ,[object Object],Оновити повідомлення,[object Object],
            ,[object Object],Копіювати в буфер обміну,[object Object],
            ,[object Object],Надіслати в Telegram (макет),[object Object],

            ,[object Object],
                ,[object Object],Telegram Bot Token (для тестування):,[object Object],
                ,[object Object],
            ,[object Object],

            ,[object Object],
                ,[object Object],Chat ID (для тестування):,[object Object],
                ,[object Object],
            ,[object Object],
        ,[object Object],
    ,[object Object],

    ,[object Object],[object Object],[object Object],
,[object Object],
,[object Object],